name: 'Docs'

on:
  # This will run tests on pushes
  # to master branch and every monday:
  push:
    branches:
      - 'main'
      - 'master'
      - 'test-cache'
  schedule:
    - cron:  '0 10 * * 1'

jobs:
  build-docs:
    runs-on: ubuntu-latest
    
    env:
      LISP: sbcl-bin

    steps:
      - uses: actions/checkout@v1
      - name: Grant All Perms on /usr/local/etc/roswell
        # This makes cache restoration possible
        run: sudo mkdir /usr/local/etc/roswell && sudo chmod -R a+rwx /usr/local/etc/roswell
      - name: Who am I
        run: whoami
      - name: Who am under SUDO
        run: sudo echo `whoami`
      - name: USSER under SUDO
        run: sudo echo "${USER}"
      - name: Cache Roswell Setup
        id: cache
        uses: actions/cache@v2
        env:
          cache-name: cache-roswell
        with:
          path: |
            ~/.roswell
            /usr/local/etc/roswell
            .qlot
          key: "${{ runner.os }}-build1-${{ env.cache-name }}-${{ hashFiles('qlfile.lock') }}"
      #- uses: 40ants/setup-lisp@test-cache
      #   if: steps.cache.outputs.cache-hit != 'true'
      - uses: 40ants/build-docs@v1
        with:
          asdf-system: docs
          # ngrok-auth-token: ${{ secrets.NGROK_AUTH_TOKEN }}
