name: 'Docs'

on:
  # This will run tests on pushes
  # to master branch and every monday:
  push:
    branches:
      - 'main'
      - 'master'
      - 'test-cache'
  schedule:
    - cron:  '0 10 * * 1'

jobs:
  build-docs:
    runs-on: ubuntu-latest
    
    env:
      LISP: sbcl-bin

    steps:
      - uses: actions/checkout@v1
      - name: Cache Roswell Setup
        uses: actions/cache@v2
        env:
          cache-name: cache-roswell
        with:
          path: ~/.roswell
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('qlfile.lock') }}
      with:
      - uses: 40ants/setup-lisp@test-cache
      - uses: 40ants/build-docs@v1
        with:
          asdf-system: docs
          # ngrok-auth-token: ${{ secrets.NGROK_AUTH_TOKEN }}

