name: tests

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "0 0 * * SUN"

jobs:
  tests:
    strategy:
      fail-fast: false # Let the workflow continue as much as possible
      matrix:
        include:
          # Linux
          - os: ubuntu-latest
            lisp: abcl-bin
          # See issue: https://github.com/40ants/setup-lisp/issues/22
          # - os: ubuntu-latest
          #   lisp: allegro
          - os: ubuntu-latest
            lisp: ccl-bin
          # See issue: https://github.com/40ants/setup-lisp/issues/16
          # - os: ubuntu-latest
          #   lisp: clasp
          - os: ubuntu-latest
            lisp: clasp-bin
          # See issue: https://github.com/40ants/setup-lisp/issues/15
          # - os: ubuntu-latest
          #   lisp: clisp
          - os: ubuntu-latest
            lisp: clisp-head
          - os: ubuntu-latest
            lisp: cmu-bin
          - os: ubuntu-latest
            lisp: ecl
          # See issue: https://github.com/40ants/setup-lisp/issues/17
          # - os: ubuntu-latest
          #   lisp: mkcl
          # See issue: https://github.com/40ants/setup-lisp/issues/18
          # - os: ubuntu-latest
          #   lisp: npt
          - os: ubuntu-latest
            lisp: sbcl
          # Just to ensure test.ros will not fail when version
          # is specified explicitly
          - os: ubuntu-latest
            lisp: sbcl/2.3.1
          - os: ubuntu-latest
            lisp: sbcl-bin

          # OSX
          - os: macos-13
            lisp: abcl-bin
          - os: macos-13
            lisp: ccl-bin
          # https://github.com/40ants/setup-lisp/issues/29
          # - os: macos-13
          #   lisp: clasp-bin
          # https://github.com/40ants/setup-lisp/issues/28
          # - os: macos-13
          #   lisp: clisp-head
          # https://github.com/40ants/setup-lisp/issues/30
          # - os: macos-13
          #   lisp: cmu-bin
          - os: macos-13
            lisp: ecl
          - os: macos-13
            lisp: sbcl-bin

          - os: macos-14
            lisp: abcl-bin
          # - os: macos-14
          #   lisp: ccl-bin
          # https://github.com/40ants/setup-lisp/issues/29
          # - os: macos-14
          #   lisp: clasp-bin
          # https://github.com/40ants/setup-lisp/issues/28
          # - os: macos-14
          #   lisp: clisp-head
          # https://github.com/40ants/setup-lisp/issues/30
          # - os: macos-14
          #   lisp: cmu-bin
          - os: macos-14
            lisp: ecl
          - os: macos-14
            lisp: sbcl-bin


          # Windows

          # https://github.com/40ants/setup-lisp/issues/27
          # - os: windows-latest
          #   lisp: abcl-bin
          # https://github.com/40ants/setup-lisp/issues/27
          # - os: windows-latest
          #   lisp: ccl-bin
          # https://github.com/40ants/setup-lisp/issues/27
          # - os: windows-latest
          #   lisp: clasp-bin
          # https://github.com/40ants/setup-lisp/issues/27
          # - os: windows-latest
          #   lisp: clisp-head
          # https://github.com/40ants/setup-lisp/issues/27
          # - os: windows-latest
          #   lisp: cmu-bin
          # https://github.com/40ants/setup-lisp/issues/27
          # - os: windows-latest
          #   lisp: ecl
          - os: windows-latest
            lisp: sbcl-bin
            

    defaults:
      run:
        shell: lispsh -eo pipefail {0}
    env:
      LISP: ${{ matrix.lisp }}
    name: test with ${{ matrix.lisp }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          # The repo already contains the qlot and qlot.lock files, and since
          # we don't want those to interfere with the current test run, we
          # clone the repository somewhere else (i.e. something different from
          # the default './')
          path: setup-lisp
      - name: Call setup-lisp with default arguments
        if: github.event_name != 'schedule'
        uses: ./setup-lisp/
      - name: Call setup-lisp and install latest
        if: github.event_name == 'schedule'
        uses: ./setup-lisp/
        with:
          roswell-version: latest
          # XXX remove this override (i.e. put "latest" back in) after the
          # following roswell issue has been solved:
          # https://github.com/roswell/roswell/issues/497
          asdf-version: 3.3.5.3
          qlot-version: latest
      - run: ros config
        # On OSX this steps fails often:
        # https://github.com/40ants/setup-lisp/issues/31
        # I don't know how to fix it, so we'll skip it for now:
        continue-on-error: true
      - run: qlot exec ros install 40ants/cl-info
      - run: pwd
      - run: ls -l -A .
      - run: ls -l .qlot/bin
      - run: qlot exec cl-info

